font_family	Input Mono Narrow
adjust_line_height 1

foreground      #f8f8f2
background		#22212C

active_tab_foreground       #f8f8f2
active_tab_background       #454158
active_tab_font_style       bold
inactive_tab_foreground     #666666
inactive_tab_background     #22212C
inactive_tab_font_style     normal

selection_foreground    none
selection_background    #454158

color0          #454158
color8          #999999

color1          #FF9580
color9          #FF9580

color2          #8AFF80
color10         #8AFF80

color3          #FFFF80
color11         #FFFF80

color4          #9580FF
color12         #9580FF

color5          #FF80BF
color13         #FF80BF

color6          #80FFEA
color14         #80FFEA

color7          #666666
color15         #ffffff