# remap prefix to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# force reload config
unbind r
bind r source-file ~/.tmux.conf

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# clean up status bar
set -g status-left ''
set -g status-right ''

# soften status bar
set -g status-style bg=#000000,fg=#aaaaaa
